#!/bin/bash
set -e

# Config
LOCAL_NAME="Local"

BASE_DIR="${HOME}/Desktop/P"
LOCAL_DIR="${BASE_DIR}/${LOCAL_NAME}"
TEMP_DIR="${HOME}/Desktop"

DEST_DIR="${HOME}/media/Downloads/ZZZ - Special/To Be Filed"
DEST_IMAGE_DIR="${DEST_DIR}/Images"

# Fix previous failures
if [ ! -d "${LOCAL_DIR}" ] && [ -d ~/Desktop/Local ]; then
	echo "Local is on the desktop; fixing..." 1>&2
	mv "${TEMP_DIR}/${LOCAL_NAME}" "${BASE_DIR}/"
fi

# Stop if there are no images to merge
if ! ls "${BASE_DIR}" | grep -v Local | grep -q '.'; then
	exit 0
fi

# Merge image directories (with mergeDir)
mv "${LOCAL_DIR}" "${TEMP_DIR}"
mergeDir.pl "${DEST_IMAGE_DIR}" "${BASE_DIR}" > /dev/null
find "${BASE_DIR}" -mindepth 1 -type d -empty -delete
mv "${TEMP_DIR}/${LOCAL_NAME}" "${BASE_DIR}/"
